### ISSUE TITLE
Linker Issue with Packet Wrapper on TCP Server

### ISSUE THREAD

**Issue by blejkowski** [SBerenji/COMP72070_Section03_Group07#9]
Packet Wrapper is causing a Linking issue among other header files. 

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1169	one or more multiply defined symbols found	SwapifyServer	C:\Users\Bryan\source\repos\SwapifyServer\x64\Debug\SwapifyServer.exe	1

**Comment by Sudhan-Dahake** [comment]
This issue is now fixed. While creating PacketWrapper i implemented the function definitions in .h file instead of .cpp file. Since, multiple .cpp files linked this .h file, it broke the "One definition rule" and caused redefinition issues. The fix was to create a PacketWrapper.cpp file and implement the function definition there.
